BEGIN;
ALTER TABLE app_roles DROP CONSTRAINT IF EXISTS app_roles_data_scope_check;
ALTER TABLE app_roles ADD CONSTRAINT app_roles_data_scope_check CHECK(data_scope IN ('company','project','warehouse','supplier','own','todo','department','projectWarehouse'));
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS data_scope text CHECK(data_scope IN ('company','project','warehouse','supplier','own','todo','department','projectWarehouse'));
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS failed_logins integer NOT NULL DEFAULT 0;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS locked_until timestamptz;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS password_changed_at timestamptz;
CREATE TABLE IF NOT EXISTS app_auth_sessions(token_hash text PRIMARY KEY,user_id text NOT NULL REFERENCES app_users(id),created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,revoked_at timestamptz,ip_address text);
CREATE INDEX IF NOT EXISTS app_sessions_user ON app_auth_sessions(user_id,expires_at);
CREATE TABLE IF NOT EXISTS app_login_attempts(id bigserial PRIMARY KEY,account text,ip_address text,success boolean NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS app_login_rate ON app_login_attempts(ip_address,created_at);
ALTER TABLE app_attachments ADD COLUMN IF NOT EXISTS content_type text;
ALTER TABLE app_attachments ADD COLUMN IF NOT EXISTS file_size bigint;
ALTER TABLE app_attachments ADD COLUMN IF NOT EXISTS sha256 text;
ALTER TABLE app_attachments ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
CREATE TABLE IF NOT EXISTS app_approval_templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),module_id text NOT NULL REFERENCES app_modules(module_id),name text NOT NULL,nodes jsonb NOT NULL,enabled boolean NOT NULL DEFAULT true,created_by text,created_at timestamptz DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS app_template_enabled ON app_approval_templates(module_id) WHERE enabled;
CREATE TABLE IF NOT EXISTS app_approval_instances(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),record_id uuid NOT NULL REFERENCES app_records(id),module_id text NOT NULL REFERENCES app_modules(module_id),template_id uuid REFERENCES app_approval_templates(id),nodes jsonb NOT NULL,current_step integer NOT NULL DEFAULT 0,current_cycle integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'pending',created_by text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS app_approval_active ON app_approval_instances(record_id) WHERE status='pending';
CREATE TABLE IF NOT EXISTS app_approval_tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),instance_id uuid NOT NULL REFERENCES app_approval_instances(id),step integer NOT NULL,cycle integer NOT NULL DEFAULT 0,assignee text NOT NULL REFERENCES app_users(id),status text NOT NULL DEFAULT 'pending',comment text,completed_at timestamptz,created_at timestamptz DEFAULT now(),todo_id uuid REFERENCES app_todos(id));
CREATE TABLE IF NOT EXISTS app_notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id text NOT NULL REFERENCES app_users(id),title text NOT NULL,message text NOT NULL,record_id uuid REFERENCES app_records(id),read_at timestamptz,created_at timestamptz DEFAULT now());
ALTER TABLE app_finance_settlements ADD COLUMN IF NOT EXISTS amount numeric(18,2);
ALTER TABLE app_finance_settlements ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'AED';
ALTER TABLE app_finance_settlements ADD COLUMN IF NOT EXISTS paid_amount numeric(18,2) NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS app_finance_payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),settlement_id uuid NOT NULL REFERENCES app_finance_settlements(id),amount numeric(18,2) NOT NULL CHECK(amount>0),reference text UNIQUE NOT NULL,paid_at timestamptz NOT NULL,created_by text NOT NULL REFERENCES app_users(id),created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS app_finance_reversals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),payment_id uuid UNIQUE NOT NULL REFERENCES app_finance_payments(id),reference text UNIQUE NOT NULL,reason text NOT NULL,amount numeric(18,2) NOT NULL CHECK(amount>0),operator text NOT NULL REFERENCES app_users(id),created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS app_equipment_usage(source_id uuid PRIMARY KEY REFERENCES app_records(id),equipment_id uuid NOT NULL REFERENCES app_records(id),completed_at timestamptz NOT NULL,work_hours numeric NOT NULL DEFAULT 0 CHECK(work_hours>=0),distance_km numeric NOT NULL DEFAULT 0 CHECK(distance_km>=0),operator text NOT NULL REFERENCES app_users(id));
INSERT INTO app_permissions SELECT module_id||':complete',module_id,'complete' FROM app_modules WHERE module_id IN ('vehicleDispatch','machineDispatch','workorder') ON CONFLICT DO NOTHING;
INSERT INTO app_role_permissions SELECT 'superAdmin',id FROM app_permissions WHERE action='complete' ON CONFLICT DO NOTHING;
INSERT INTO app_role_permissions SELECT 'driver',id FROM app_permissions WHERE module_id='vehicleDispatch' AND action IN ('view','complete') ON CONFLICT DO NOTHING;
INSERT INTO app_role_permissions SELECT 'operator',id FROM app_permissions WHERE module_id='machineDispatch' AND action IN ('view','complete') ON CONFLICT DO NOTHING;
INSERT INTO app_role_permissions SELECT 'driver',id FROM app_permissions WHERE module_id='vehicleEquipment' AND action='view' ON CONFLICT DO NOTHING;
INSERT INTO app_role_permissions SELECT 'operator',id FROM app_permissions WHERE module_id='engineeringEquipment' AND action='view' ON CONFLICT DO NOTHING;
UPDATE app_roles SET data_scope='todo'  WHERE id IN ('driver','operator') AND data_scope='own';
INSERT INTO app_schema_migrations(version) VALUES('business-v4') ON CONFLICT DO NOTHING;
COMMIT;
