package com.jada.severe.service;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import java.util.*;
@Service
public class AccessService {
 @org.springframework.beans.factory.annotation.Value("${app.include-test-data:true}") private boolean testData;
 private final JdbcTemplate db; private final HttpServletRequest request;
 public AccessService(JdbcTemplate db,HttpServletRequest request){this.db=db;this.request=request;}
 public String user(){Object u=request.getAttribute("authenticatedUser");return u==null?"anonymous":u.toString();}
 public String requestNo(){Object v=request.getAttribute("requestNo");if(v==null){v=UUID.randomUUID().toString();request.setAttribute("requestNo",v);}return v.toString();}
 public List<Map<String,Object>> roles(){if(user().equals("anonymous"))return List.of();var r=db.queryForList("select r.* from app_roles r join app_user_roles ur on ur.role_id=r.id join app_users u on u.id=ur.user_id where u.id=? and u.enabled",user());String h=request.getHeader("X-User-Role");if(h!=null){r=r.stream().filter(x->h.equals(x.get("id"))).toList();}if(r.isEmpty())deny();return r;}
 public boolean allowed(String module,String action){if(action.equals("view")&&Set.of("users","roleperm").contains(module)&&!allowed("system","manage"))return false;if(action.equals("view")&&module.equals("audit")&&!allowed("system","audit"))return false;if(user().equals("anonymous"))return action.equals("view")&&module.equals("engineeringEquipment");for(var r:roles())if(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_role_permissions rp join app_permissions p on p.id=rp.permission_id where rp.role_id=? and p.module_id=? and p.action=?)",Boolean.class,r.get("id"),module,action)))return true;return false;}
 public void require(String m,String a){if(!allowed(m,a))deny();}
 public String scope(){if(user().equals("anonymous"))return "company";var scopes=roles().stream().map(r->r.get("data_scope").toString()).toList();String limit=db.queryForObject("select data_scope from app_users where id=?",String.class,user());if(limit!=null){if(!scopes.contains("company")&&!scopes.contains(limit))deny();scopes=List.of(limit);}String h=request.getHeader("X-Data-Scope");if(h!=null){if(!Set.of("company","project","warehouse","supplier","own","todo","department","projectWarehouse").contains(h)||(!scopes.contains("company")&&!scopes.contains(h)))deny();return h;}return scopes.contains("company")?"company":scopes.get(0);}
 public String filter(List<Object> args){String s=scope();String test=testData?"":" and not is_test";if(s.equals("company"))return test;args.add(user());return test+switch(s){case "own" -> " and created_by=?";case "todo" -> {args.add(user());args.add(user());yield " and (created_by=? or id in (select record_id from app_todos where assignee=? and status='pending') or id in (select (r.payload->>'equipmentId')::uuid from app_records r join app_todos t on t.record_id=r.id where t.assignee=? and t.status='pending' and r.payload->>'equipmentId' ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'))";}case "project" -> " and project_name=(select project_name from app_users where id=?)";case "warehouse" -> " and payload->>'warehouseId'=(select warehouse_id from app_users where id=?)";case "supplier" -> " and payload->>'supplierId'=(select supplier_id from app_users where id=?)";case "projectWarehouse" -> {args.add(user());yield " and project_name=(select project_name from app_users where id=?) and payload->>'warehouseId'=(select warehouse_id from app_users where id=?)";}case "department" -> " and payload->>'departmentId'=(select department_id from app_users where id=?)";default -> throw new IllegalStateException();};}
 public void record(String m,UUID id){require(m,"view");var args=new ArrayList<Object>();args.add(m);args.add(id);String f=id.equals(request.getAttribute("approvalRecordId"))?"":filter(args);if(!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_records where module_id=? and id=? and deleted_at is null"+f+")",Boolean.class,args.toArray())))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"记录不存在或不在数据范围内");}
 public void deny(){throw new ResponseStatusException(HttpStatus.FORBIDDEN,"无权限操作");}
 public Map<String,Object> me(){var result=new LinkedHashMap<String,Object>();result.put("id",user());result.put("account",user());var assigned=roles();result.put("roles",assigned);result.put("dataScope",scope());if(!user().equals("anonymous")){var profile=db.queryForMap("select name,project_name,warehouse_id,supplier_id,department_id from app_users where id=?",user());result.put("name",profile.get("name"));result.put("profile",profile);result.put("role",assigned.get(0).get("id"));result.put("roleName",assigned.get(0).get("name"));result.put("approvalNodes",db.queryForList("select distinct node->>'nodeName' from app_approval_templates t cross join lateral jsonb_array_elements(t.nodes) node where t.enabled and jsonb_exists(node->'assignees',?)",String.class,user()));}return result;}

 public List<Map<String,Object>> permissions(){var out=new ArrayList<Map<String,Object>>();for(var r:roles())out.addAll(db.queryForList("select p.* from app_permissions p join app_role_permissions rp on rp.permission_id=p.id where rp.role_id=?",r.get("id")));return out;}
}
