package com.jada.severe.service;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;
@Service
public class AdminService {
 @org.springframework.beans.factory.annotation.Value("${app.include-test-data:true}") private boolean tests;
 private final JdbcTemplate db;private final AccessService access;private final AuditService audit;
 public AdminService(JdbcTemplate db,AccessService access,AuditService audit){this.db=db;this.access=access;this.audit=audit;}
 public List<Map<String,Object>> list(String type){access.require("system","manage");return db.queryForList("select "+columns(type)+" from "+table(type)+(tests?"":" where not is_test")+" order by id");}
 private String columns(String type){return type.equals("users")?"id,name,enabled,project_name,warehouse_id,supplier_id,department_id,data_scope,password_changed_at":"id,name,data_scope";}
 private String table(String type){return switch(type){case "users"->"app_users";case "roles"->"app_roles";default->throw new ResponseStatusException(HttpStatus.NOT_FOUND);};}
 public Map<String,Object> get(String t,String id){access.require("system","manage");var rows=db.queryForList("select "+columns(t)+" from "+table(t)+" where id=?"+(tests?"":" and not is_test"),id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"账号或角色不存在");var row=rows.get(0);if(t.equals("users"))row.put("roles",db.queryForList("select role_id from app_user_roles where user_id=?",String.class,id));return row;}
 @Transactional public Map<String,Object> save(String type,String id,Map<String,Object> p,boolean create){access.require("system","manage");if(id==null||id.isBlank()||p.get("name")==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"id/name 必填");Object before=create?null:get(type,id);
 if(type.equals("users")){if(create)db.update("insert into app_users(id,name) values(?,?)",id,p.get("name"));db.update("update app_users set name=?,enabled=?,project_name=?,warehouse_id=?,supplier_id=?,department_id=? where id=?",p.get("name"),p.getOrDefault("enabled",true),p.get("projectName"),p.get("warehouseId"),p.get("supplierId"),p.get("departmentId"),id);if(p.containsKey("roles")){db.update("delete from app_user_roles where user_id=?",id);for(Object role:(List<?>)p.get("roles"))db.update("insert into app_user_roles values(?,?)",id,role.toString());}}
 else{String scope=p.getOrDefault("dataScope","own").toString();if(create)db.update("insert into app_roles(id,name,data_scope) values(?,?,?)",id,p.get("name"),scope);else db.update("update app_roles set name=?,data_scope=? where id=?",p.get("name"),scope,id);}
 if(type.equals("users")&&p.containsKey("dataScope")){String limit=Objects.toString(p.get("dataScope"),null);if(limit!=null&&!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_user_roles ur join app_roles r on r.id=ur.role_id where ur.user_id=? and r.data_scope in ('company',?))",Boolean.class,id,limit)))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"账号范围不能超过角色授权");db.update("update app_users set data_scope=? where id=?",limit,id);}
 if(create&&id.startsWith("QA-"))db.update("update "+table(type)+" set is_test=true where id=?",id);
 var after=get(type,id);audit.log(type,null,create?"create":"edit",before,after,null,null);return after;}
 public List<Map<String,Object>> rolePermissions(String id){access.require("system","manage");return db.queryForList("select p.* from app_permissions p join app_role_permissions rp on rp.permission_id=p.id where rp.role_id=?",id);}
 @Transactional public void setPermissions(String id,List<String> permissions){access.require("system","manage");Object before=rolePermissions(id);get("roles",id);db.update("delete from app_role_permissions where role_id=?",id);for(String permission:new HashSet<>(permissions))db.update("insert into app_role_permissions values(?,?)",id,permission);audit.log("roleperm",null,"permissions",before,permissions,null,null);}
 public List<Map<String,Object>> logs(String moduleId,String recordId,String operator,String action){access.require("system","audit");var args=new ArrayList<Object>();StringBuilder where=new StringBuilder("1=1");for(var e:Map.of("module_id",moduleId==null?"":moduleId,"record_id::text",recordId==null?"":recordId,"operator",operator==null?"":operator,"action",action==null?"":action).entrySet())if(!e.getValue().isBlank()){where.append(" and ").append(e.getKey()).append("=?");args.add(e.getValue());}var out=db.queryForList("select * from app_audit_logs where "+where+" order by id desc limit 500",args.toArray());for(var row:out){row.put("before_data",audit.parse(row.get("before_data")));row.put("after_data",audit.parse(row.get("after_data")));}audit.log("audit",null,"sensitiveQuery",null,Map.of("count",out.size()),null,null);return out;}
 public List<Map<String,Object>> todos(boolean my){if(access.user().equals("anonymous"))access.deny();if(!my)access.require("system","manage");return my?db.queryForList("select * from app_todos where assignee=? order by created_at desc",access.user()):db.queryForList("select * from app_todos order by created_at desc limit 500");}
 @Transactional public void complete(UUID id){var rows=db.queryForList("select * from app_todos where id=? and assignee=? for update",id,access.user());if(rows.isEmpty())access.deny();var todo=rows.get(0);var source=db.queryForMap("select module_id,status,payload::text as payload from app_records where id=?",todo.get("record_id"));String status=source.get("status").toString();if(Set.of("vehicleDispatch","machineDispatch").contains(source.get("module_id"))&&!"completed".equals(audit.read(source.get("payload").toString()).get("executionStatus")))throw new ResponseStatusException(HttpStatus.CONFLICT,"执行待办必须通过任务完成接口提交真实执行记录");if(Set.of("submitted","reviewing").contains(status))throw new ResponseStatusException(HttpStatus.CONFLICT,"审批待办须先通过流程接口审批或驳回");db.update("update app_todos set status='completed',completed_at=now() where id=?",id);audit.log("todos",(UUID)todo.get("record_id"),"completeTodo",todo,Map.of("status","completed"),null,null);}
 public List<Map<String,Object>> settlements(){access.require("expensePaymentRecord","view");var args=new ArrayList<Object>();String scope=access.filter(args);return db.queryForList("select * from app_finance_settlements where source_id in (select id from app_records where deleted_at is null"+scope+") order by created_at desc limit 500",args.toArray());}
}
