package com.jada.severe.service;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import jakarta.servlet.http.HttpServletRequest;
import java.util.*;
import java.math.BigDecimal;

@Service
public class ApprovalService {
 @org.springframework.beans.factory.annotation.Value("${app.include-test-data:true}") private boolean tests;
 private final JdbcTemplate db;private final AccessService access;private final AuditService audit;private final ObjectProvider<ModuleService> modules;private final HttpServletRequest request;
 public ApprovalService(JdbcTemplate db,AccessService access,AuditService audit,ObjectProvider<ModuleService> modules,HttpServletRequest request){this.db=db;this.access=access;this.audit=audit;this.modules=modules;this.request=request;}
 private ResponseStatusException conflict(String reason){return new ResponseStatusException(HttpStatus.CONFLICT,reason);}
 private void eligible(String module,String user){if(!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_users u join app_user_roles ur on ur.user_id=u.id join app_role_permissions rp on rp.role_id=ur.role_id join app_permissions p on p.id=rp.permission_id where u.id=? and u.enabled and (? or not u.is_test) and p.module_id=? and p.action='approve')",Boolean.class,user,tests,module)))throw conflict("审批人未启用或没有该模块审批权限: "+user);}
 private List<Map<String,Object>> nodes(Object value){if(!(value instanceof List<?> list)||list.isEmpty()||list.size()>20)throw conflict("审批节点必须为1至20个");var result=new ArrayList<Map<String,Object>>();for(Object item:list){if(!(item instanceof Map<?,?> map)||map.get("nodeName")==null||!(map.get("assignees") instanceof List<?> assignees)||assignees.isEmpty())throw conflict("节点必须包含 nodeName 和 assignees");var node=new LinkedHashMap<String,Object>();map.forEach((k,v)->node.put(k.toString(),v));if(!Set.of("all","any").contains(node.getOrDefault("mode","any")))throw conflict("节点 mode 仅支持 all/any");result.add(node);}return result;}
 @Transactional public Map<String,Object> saveTemplate(UUID id,Map<String,Object> body){access.require("approvalTemplate","edit");String module=Objects.toString(body.get("moduleId"),"");var nodes=nodes(body.get("nodes"));for(var node:nodes)for(Object user:(List<?>)node.get("assignees"))eligible(module,user.toString());boolean enabled=!Boolean.FALSE.equals(body.get("enabled"));if(enabled)db.update("update app_approval_templates set enabled=false where module_id=?",module);if(id==null){id=UUID.randomUUID();db.update("insert into app_approval_templates(id,module_id,name,nodes,enabled,created_by) values(?,?,?,?::jsonb,?,?)",id,module,Objects.toString(body.get("name"),"审批模板"),audit.json(nodes),enabled,access.user());}else if(db.update("update app_approval_templates set module_id=?,name=?,nodes=?::jsonb,enabled=? where id=?",module,Objects.toString(body.get("name"),"审批模板"),audit.json(nodes),enabled,id)==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"模板不存在");audit.log("approvalTemplate",null,"saveTemplate",null,Map.of("id",id,"nodes",nodes),null,null);return Map.of("id",id);}
 public List<Map<String,Object>> templates(){access.require("approvalTemplate","view");var rows=db.queryForList("select * from app_approval_templates order by created_at desc");for(var row:rows)row.put("nodes",audit.parse(row.get("nodes")));return rows;}
 public void open(String module,UUID record,Map<String,Object> payload){
  if(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_approval_instances where record_id=? and status='pending')",Boolean.class,record)))throw conflict("单据已有审批实例");
  var templates=db.queryForList("select * from app_approval_templates where module_id=? and enabled",module);UUID template=null;List<Map<String,Object>> selected;
  if(templates.isEmpty()){var users=db.queryForList("select distinct u.id from app_users u join app_user_roles ur on ur.user_id=u.id join app_role_permissions rp on rp.role_id=ur.role_id join app_permissions p on p.id=rp.permission_id where u.enabled and (? or not u.is_test) and p.module_id=? and p.action='approve' order by u.id",String.class,tests,module);if(users.isEmpty())throw conflict("没有可用审批人");selected=List.of(Map.of("nodeName","业务审批","assignees",users,"mode","any"));}
  else{template=(UUID)templates.get(0).get("id");selected=nodes(audit.parse(templates.get(0).get("nodes")));}
  BigDecimal amount=BigDecimal.ZERO;for(String key:List.of("amount","金额","合同金额","申请金额","报销金额"))if(payload.get(key)!=null){try{amount=new BigDecimal(payload.get(key).toString());}catch(NumberFormatException e){throw conflict("金额不是有效数字");}break;}
  var applicable=new ArrayList<Map<String,Object>>();for(var node:selected){BigDecimal min=node.get("minAmount")==null?null:new BigDecimal(node.get("minAmount").toString()),max=node.get("maxAmount")==null?null:new BigDecimal(node.get("maxAmount").toString());if((min==null||amount.compareTo(min)>=0)&&(max==null||amount.compareTo(max)<=0))applicable.add(node);}if(applicable.isEmpty())throw conflict("没有匹配的审批节点");
  UUID instance=db.queryForObject("insert into app_approval_instances(record_id,module_id,template_id,nodes,created_by) values(?,?,?,?::jsonb,?) returning id",UUID.class,record,module,template,audit.json(applicable),access.user());assign(instance,record,module,0,0,applicable.get(0));audit.log(module,record,"approvalCreated",null,Map.of("instanceId",instance,"nodes",applicable),null,null);
 }
 private void assign(UUID instance,UUID record,String module,int step,int cycle,Map<String,Object> node){
  for(Object item:new LinkedHashSet<>((List<?>)node.get("assignees"))){String user=item.toString();eligible(module,user);UUID todo=db.queryForObject("insert into app_todos(record_id,assignee) values(?,?) on conflict(record_id,assignee) where status='pending' do update set status='pending' returning id",UUID.class,record,user);db.update("insert into app_approval_tasks(instance_id,step,cycle,assignee,todo_id) values(?,?,?,?,?)",instance,step,cycle,user,todo);db.update("insert into app_notifications(user_id,title,message,record_id) values(?,?,?,?)",user,"待办审批",node.get("nodeName").toString(),record);}
 }
 public boolean active(UUID record){return Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_approval_instances where record_id=? and status='pending')",Boolean.class,record));}
 public boolean finalizing(){return Boolean.TRUE.equals(request.getAttribute("approvalFinalizing"));}
 @Transactional public Map<String,Object> decideRecord(UUID record,String action,Map<String,Object> body){var tasks=db.queryForList("select t.id from app_approval_tasks t join app_approval_instances i on i.id=t.instance_id where i.record_id=? and i.status='pending' and t.status='pending' and t.step=i.current_step and t.cycle=i.current_cycle and t.assignee=?",UUID.class,record,access.user());if(tasks.isEmpty())access.deny();return task(tasks.get(0),action,body);}
 @Transactional public Map<String,Object> task(UUID id,String action,Map<String,Object> body){
  var found=db.queryForList("select i.* from app_approval_instances i join app_approval_tasks t on t.instance_id=i.id where t.id=? for update of i",id);if(found.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"审批任务不存在");var instance=found.get(0);UUID iid=(UUID)instance.get("id"),record=(UUID)instance.get("record_id");String module=instance.get("module_id").toString();int step=((Number)instance.get("current_step")).intValue(),cycle=((Number)instance.get("current_cycle")).intValue();
  access.require(module,action.equals("reject")||action.equals("return")?"reject":"approve");access.record(module,record);var t=db.queryForMap("select * from app_approval_tasks where id=? for update",id);if(!access.user().equals(t.get("assignee"))||!"pending".equals(t.get("status"))||!"pending".equals(instance.get("status"))||((Number)t.get("step")).intValue()!=step||((Number)t.get("cycle")).intValue()!=cycle)access.deny();
  String comment=Objects.toString(body.get("comment"),"");var nodes=nodes(audit.parse(instance.get("nodes")));
  if(action.equals("transfer")||action.equals("addSign")){String assignee=Objects.toString(body.get("assignee"),"");eligible(module,assignee);if(assignee.equals(access.user()))throw conflict("不能转交或加签给本人");if(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_approval_tasks where instance_id=? and step=? and cycle=? and assignee=? and status='pending')",Boolean.class,iid,step,cycle,assignee)))throw conflict("该审批人已有待办");if(action.equals("transfer")){db.update("update app_approval_tasks set status='transferred',comment=?,completed_at=now() where id=?",comment,id);completeTodo(t);}else{nodes.get(step).put("mode","all");db.update("update app_approval_instances set nodes=?::jsonb where id=?",audit.json(nodes),iid);}assign(iid,record,module,step,cycle,Map.of("nodeName",nodes.get(step).get("nodeName"),"assignees",List.of(assignee)));}
  else if(action.equals("return")){int target=((Number)body.getOrDefault("targetStep",-1)).intValue();if(target>=step||target < -1)throw conflict("退回节点必须早于当前节点");cancel(iid,record);if(target<0){db.update("update app_approval_instances set status='returned',updated_at=now() where id=?",iid);finish(module,record,"reject",body);}else{db.update("update app_approval_instances set current_step=?,current_cycle=current_cycle+1,updated_at=now() where id=?",target,iid);assign(iid,record,module,target,cycle+1,nodes.get(target));}}
  else if(action.equals("reject")){cancel(iid,record);db.update("update app_approval_tasks set status='rejected',comment=?,completed_at=now() where id=?",comment,id);db.update("update app_approval_instances set status='rejected',updated_at=now() where id=?",iid);finish(module,record,"reject",body);}
  else if(action.equals("approve")){db.update("update app_approval_tasks set status='approved',comment=?,completed_at=now() where id=?",comment,id);completeTodo(t);int remaining=db.queryForObject("select count(*) from app_approval_tasks where instance_id=? and step=? and cycle=? and status='pending'",Integer.class,iid,step,cycle);boolean done=Objects.toString(nodes.get(step).getOrDefault("mode","any")).equals("any")||remaining==0;if(done){cancel(iid,record);if(step+1>=nodes.size()){finish(module,record,"approve",body);db.update("update app_approval_instances set status='approved',updated_at=now() where id=?",iid);}else{db.update("update app_approval_instances set current_step=current_step+1,current_cycle=current_cycle+1,updated_at=now() where id=?",iid);assign(iid,record,module,step+1,cycle+1,nodes.get(step+1));String status=db.queryForObject("select status from app_records where id=?",String.class,record);if(status.equals("submitted"))finish(module,record,"startReview",Map.of());}}}
  else throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"不支持的审批动作");
  audit.log(module,record,"approvalTask:"+action,t,Map.of("taskId",id,"comment",comment,"body",body),null,null);return Map.of("success",true,"data",flow(module,record),"message","审批操作已存档");
 }
 private void completeTodo(Map<String,Object> task){db.update("update app_todos set status='completed',completed_at=now() where id=?",task.get("todo_id"));}
 private void cancel(UUID instance,UUID record){db.update("update app_todos set status='completed',completed_at=now() where id in (select todo_id from app_approval_tasks where instance_id=? and status='pending')",instance);db.update("update app_approval_tasks set status='cancelled',completed_at=now() where instance_id=? and status='pending'",instance);}
 private void finish(String module,UUID record,String action,Map<String,Object> body){request.setAttribute("approvalFinalizing",true);request.setAttribute("approvalRecordId",record);try{modules.getObject().transition(module,record,action,body);}finally{request.removeAttribute("approvalFinalizing");request.removeAttribute("approvalRecordId");}}
 public Map<String,Object> flow(String module,UUID record){access.require(module,"view");var rows=db.queryForList("select * from app_approval_instances where module_id=? and record_id=? order by created_at desc limit 1",module,record);if(rows.isEmpty()){access.record(module,record);return Map.of("nodes",List.of(),"tasks",List.of());}var instance=rows.get(0);if(!access.allowed("system","manage")&&!access.user().equals(instance.get("created_by"))&&!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_approval_tasks where instance_id=? and assignee=?)",Boolean.class,instance.get("id"),access.user())))access.record(module,record);instance.put("nodes",audit.parse(instance.get("nodes")));instance.put("tasks",db.queryForList("select * from app_approval_tasks where instance_id=? order by created_at",instance.get("id")));return instance;}
 public void cancelRecord(UUID record){var ids=db.queryForList("select id from app_approval_instances where record_id=? and status='pending' for update",UUID.class,record);for(UUID id:ids){cancel(id,record);db.update("update app_approval_instances set status='cancelled',updated_at=now() where id=?",id);}}
}
