package com.jada.severe.service;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import java.util.*;
import java.math.BigDecimal;
import java.time.LocalDate;
@Service
public class DomainService {
 private final JdbcTemplate db;private final AccessService access;private final AuditService audit;
 public DomainService(JdbcTemplate db,AccessService access,AuditService audit){this.db=db;this.access=access;this.audit=audit;}
 private String text(Map<String,Object> p,String... keys){for(String key:keys)if(p.get(key)!=null&&!p.get(key).toString().isBlank())return p.get(key).toString();return null;}
 private void fail(String reason){throw new ResponseStatusException(HttpStatus.CONFLICT,reason);}
 private UUID equipment(Map<String,Object> p){String value=text(p,"equipmentId");if(value==null)fail("必须关联 equipmentId");UUID id=UUID.fromString(value);if(!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_records where id=? and module_id in ('engineeringEquipment','vehicleEquipment') and deleted_at is null)",Boolean.class,id)))fail("关联设备不存在");db.queryForObject("select id from app_records where id=? for update",UUID.class,id);return id;}
 private void patch(UUID id,Map<String,Object> payload,String action){var before=db.queryForMap("select module_id,status,payload::text as payload from app_records where id=?",id);db.update("update app_records set payload=payload || ?::jsonb,updated_by=?,updated_at=now() where id=?",audit.json(payload),access.user(),id);audit.log(before.get("module_id").toString(),id,action,before,db.queryForMap("select status,payload::text as payload from app_records where id=?",id),before.get("status").toString(),before.get("status").toString());}
 public void apply(String module,UUID record,String action,Map<String,Object> p){
  if(action.equals("approve"))switch(module){
   case "person" -> {for(String field:List.of("证照有效期","保险/劳务有效期"))if(text(p,field)!=null&&LocalDate.parse(text(p,field)).isBefore(LocalDate.now()))fail("人员证照或保险已过期");patch(record,Map.of("qualified",true),"personQualified");}
   case "vehicleEquipment" -> {String driver=text(p,"driverId");if(driver!=null){person(UUID.fromString(driver),"司机");patch(record,Map.of("driverId",driver),"driverBinding");}}
   case "assetLife" -> {UUID asset=equipment(p);String kind=text(p,"operationType","事项类型");if(kind==null)fail("事项类型必填");if(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_equipment_reservations where equipment_id=?)",Boolean.class,asset))&&!kind.equals("盘点"))fail("占用设备不能调拨或处置");var change=new LinkedHashMap<String,Object>();switch(kind){case "盘点" -> {change.put("lastInventoryRecordId",record.toString());change.put("lastInventoryAt",java.time.OffsetDateTime.now().toString());}case "调拨" -> {String location=text(p,"location","目标地点"),custodian=text(p,"custodian","保管单位");if(location==null||custodian==null)fail("调拨必须指定 location/custodian");change.put("现设备地点",location);change.put("location",location);change.put("管理单位",custodian);change.put("custodian",custodian);}case "减值" -> {String value=text(p,"carryingValue","账面价值");if(value==null||new BigDecimal(value).signum()<0)fail("账面价值无效");change.put("carryingValue",new BigDecimal(value));}case "报废","处置" -> {change.put("equipmentStatus","disabled");change.put("在用/闲置","停用");change.put("disposalRecordId",record.toString());}default -> fail("不支持的资产事项类型");}patch(asset,change,"assetLife:"+kind);db.update("insert into app_business_links values(?,?,'assetLife') on conflict do nothing",record,asset);}
   case "inspection" -> {UUID asset=equipment(p);String result=text(p,"inspectionResult");if(!Set.of("passed","failed").contains(Objects.toString(result,"")))fail("inspectionResult 必须为 passed/failed");if(result.equals("failed")&&Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_equipment_reservations where equipment_id=?)",Boolean.class,asset)))fail("占用设备须先结束对应业务，再提交停用检查结论");patch(asset,result.equals("failed")?Map.of("equipmentStatus","disabled","在用/闲置","停用","完好状态","损坏","lastInspectionId",record.toString()):Map.of("lastInspectionId",record.toString()),"inspectionResult");}
   case "standards" -> patch(record,Map.of("published",true,"publishedAt",java.time.OffsetDateTime.now().toString()),"standardPublished");
   case "users" -> provisionUser(record,p);
   case "roleperm" -> provisionRole(record,p);
   case "notice" -> {String channel=Objects.toString(text(p,"发送渠道","channel"),"站内信");if(!channel.equals("站内信"))fail("该发送渠道未配置服务商，请使用站内信");Object recipients=p.get("recipientIds");List<?> users=recipients instanceof List<?> list?list:Arrays.asList(Objects.toString(text(p,"接收人"),"").split(","));if(users.isEmpty())fail("接收人必填");for(Object user:users){String id=user.toString().trim();if(!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_users where id=? and enabled)",Boolean.class,id)))fail("接收账号不存在或已停用");db.update("insert into app_notifications(user_id,title,message,record_id) values(?,?,?,?)",id,Objects.toString(text(p,"通知标题","title"),"系统通知"),Objects.toString(text(p,"message","跳转与重试规则"),""),record);}patch(record,Map.of("delivered",true),"notificationDelivered");}
   default -> {}
  }
  if(action.equals("archive")&&module.equals("users")){access.require("system","manage");String user=text(p,"identityId","登录账号");if(user!=null){if(user.equals(access.user()))fail("不能停用当前登录账号");db.update("update app_users set enabled=false where id=?",user);db.update("update app_auth_sessions set revoked_at=now() where user_id=?",user);}}
 }
 public void person(UUID id,String type){var rows=db.queryForList("select payload::text as payload,status from app_records where id=? and module_id='person' and deleted_at is null",id);if(rows.isEmpty()||!rows.get(0).get("status").equals("approved"))fail("关联人员未通过资质审批");var p=audit.read(rows.get(0).get("payload").toString());if(!type.equals(text(p,"人员类型")))fail("关联人员类型不匹配");for(String key:List.of("证照有效期","保险/劳务有效期"))if(text(p,key)!=null&&LocalDate.parse(text(p,key)).isBefore(LocalDate.now()))fail("关联人员证照已过期");}
 private String scope(String text){return switch(Objects.toString(text,"own")){case "全公司","company" -> "company";case "所属供应商","supplier" -> "supplier";case "项目+仓库","projectWarehouse" -> "projectWarehouse";case "本人任务","todo" -> "todo";case "所属项目","project" -> "project";case "所属仓库","warehouse" -> "warehouse";case "本部门","department" -> "department";case "本人创建","own" -> "own";default -> throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"数据范围无效");};}
 private String role(String name){var aliases=Map.of("供应商用户","supplier","司机移动端","driver","工程设备操作员","operator");if(aliases.containsKey(name))return aliases.get(name);var ids=db.queryForList("select id from app_roles where id=? or name=?",String.class,name,name);if(ids.size()!=1)fail("角色不存在或名称不唯一");return ids.get(0);}
 private void provisionUser(UUID record,Map<String,Object> p){access.require("system","manage");String id=text(p,"account","登录账号"),name=text(p,"name","用户姓名"),r=text(p,"roleId","绑定主角色");if(id==null||name==null||r==null)fail("账号、姓名和主角色必填");String role=role(r);if(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_users where id=?)",Boolean.class,id))&&!id.equals(text(p,"identityId")))fail("账号已存在，请通过账号管理接口更新");db.update("insert into app_users(id,name,enabled,project_name,warehouse_id,supplier_id,department_id) values(?,?,?,?,?,?,?) on conflict(id) do update set name=excluded.name,enabled=excluded.enabled,project_name=excluded.project_name,warehouse_id=excluded.warehouse_id,supplier_id=excluded.supplier_id,department_id=excluded.department_id",id,name,!Set.of("停用","锁定").contains(Objects.toString(p.get("账号状态"),"启用")),p.get("projectName"),p.get("warehouseId"),p.get("supplierId"),p.get("departmentId"));db.update("insert into app_user_roles values(?,?) on conflict do nothing",id,role);String restriction=text(p,"dataScope","数据范围");if(restriction!=null){String limit=scope(restriction);if(!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from app_roles where id=? and data_scope in ('company',?))",Boolean.class,role,limit)))fail("账号数据范围不能超过角色授权");db.update("update app_users set data_scope=? where id=?",limit,id);}patch(record,Map.of("identityId",id),"accountProvisioned");}
 private void provisionRole(UUID record,Map<String,Object> p){access.require("system","manage");String id=text(p,"roleId"),name=text(p,"角色名称","name");if(id==null||name==null)fail("roleId/角色名称必填");db.update("insert into app_roles(id,name,data_scope) values(?,?,?) on conflict(id) do update set name=excluded.name,data_scope=excluded.data_scope",id,name,scope(text(p,"dataScope","默认数据范围")));if(p.get("permissions") instanceof List<?> permissions){db.update("delete from app_role_permissions where role_id=?",id);for(Object permission:permissions)db.update("insert into app_role_permissions values(?,?)",id,permission.toString());}Object users=p.get("userIds");if(users instanceof List<?> list)for(Object user:list)db.update("insert into app_user_roles values(?,?) on conflict do nothing",user.toString(),id);patch(record,Map.of("identityId",id),"roleProvisioned");}
}
