package com.jada.severe.service;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.http.HttpStatus;
import java.math.*;
import java.time.OffsetDateTime;
import java.util.*;
@Service
public class FinanceService {
 private final JdbcTemplate db;private final AccessService access;private final AuditService audit;
 public FinanceService(JdbcTemplate db,AccessService access,AuditService audit){this.db=db;this.access=access;this.audit=audit;}
 private BigDecimal money(Object value){try{var amount=new BigDecimal(value.toString()).setScale(2,RoundingMode.UNNECESSARY);if(amount.signum()<0)throw new IllegalArgumentException();return amount;}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"金额须为非负数且最多两位小数");}}
 private Map<String,Object> settlement(UUID id,String action){access.require("expensePaymentRecord",action);var rows=db.queryForList("select s.*,r.module_id from app_finance_settlements s join app_records r on r.id=s.source_id where s.id=? for update of s",id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"结算单不存在");var row=rows.get(0);access.record(row.get("module_id").toString(),(UUID)row.get("source_id"));return row;}
 @Transactional public Map<String,Object> confirm(UUID id,Map<String,Object> body){var before=settlement(id,"approve");var amount=money(body.get("amount"));if(amount.compareTo((BigDecimal)before.get("paid_amount"))<0)throw new ResponseStatusException(HttpStatus.CONFLICT,"应付金额不能低于已付款金额");String currency=Objects.toString(body.getOrDefault("currency",before.get("currency")));if(!Set.of("AED","SAR","USD","CNY").contains(currency))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"币种无效");if(((BigDecimal)before.get("paid_amount")).signum()>0&&!currency.equals(before.get("currency")))throw new ResponseStatusException(HttpStatus.CONFLICT,"已付款结算单不能变更币种");db.update("update app_finance_settlements set amount=?,currency=?,status=case when paid_amount=? then 'paid' when paid_amount>0 then 'partial' else 'pending' end where id=?",amount,currency,amount,id);var after=db.queryForMap("select * from app_finance_settlements where id=?",id);audit.log("expensePaymentRecord",(UUID)before.get("source_id"),"settlementConfirm",before,after,null,null);return after;}
 @Transactional public Map<String,Object> pay(UUID id,Map<String,Object> body){
  var before=settlement(id,"approve");BigDecimal amount=money(body.get("amount"));if(amount.signum()<=0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"付款金额必须大于0");String reference=Objects.toString(body.get("reference"),"").trim();if(reference.isEmpty()||reference.length()>100)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"银行流水号必填且最多100字符");
  var existing=db.queryForList("select * from app_finance_payments where reference=?",reference);if(!existing.isEmpty()){var row=existing.get(0);if(!id.equals(row.get("settlement_id"))||amount.compareTo((BigDecimal)row.get("amount"))!=0)throw new ResponseStatusException(HttpStatus.CONFLICT,"该银行流水号已经用于其他付款");return row;}
  if(before.get("amount")==null)throw new ResponseStatusException(HttpStatus.CONFLICT,"先确认应付金额与币种");BigDecimal paid=((BigDecimal)before.get("paid_amount")).add(amount);if(paid.compareTo((BigDecimal)before.get("amount"))>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"付款超过应付余额");OffsetDateTime time;try{time=OffsetDateTime.parse(Objects.toString(body.get("paidAt")));}catch(Exception e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"paidAt 必须为含时区的付款时间");}if(time.isAfter(OffsetDateTime.now().plusMinutes(5)))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"付款时间不能晚于当前时间");
  UUID payment=db.queryForObject("insert into app_finance_payments(settlement_id,amount,reference,paid_at,created_by) values(?,?,?,?,?) returning id",UUID.class,id,amount,reference,time,access.user());
  db.update("update app_finance_settlements set paid_amount=?,status=? where id=?",paid,paid.compareTo((BigDecimal)before.get("amount"))==0?"paid":"partial",id);
  var payload=new LinkedHashMap<String,Object>(body);var sourcePayload=audit.read(db.queryForObject("select payload::text from app_records where id=?",String.class,before.get("source_id")));for(String scopeField:List.of("warehouseId","supplierId","departmentId","projectName"))if(sourcePayload.get(scopeField)!=null)payload.put(scopeField,sourcePayload.get(scopeField));payload.put("paymentId",payment.toString());payload.put("settlementId",id.toString());payload.put("sourceRecordId",before.get("source_id").toString());payload.put("币种",before.get("currency"));payload.put("本次付款金额",amount);payload.put("银行流水号",reference);payload.put("付款状态","已付款");payload.put("status","approved");
  UUID record=db.queryForObject("insert into app_records(module_id,record_no,title,status,payload,created_by,updated_by,project_name,is_test) select 'expensePaymentRecord',?,?,'approved',?::jsonb,?,?,project_name,is_test from app_records where id=? returning id",UUID.class,"PAY-"+payment,"付款 "+reference,audit.json(payload),access.user(),access.user(),before.get("source_id"));db.update("insert into app_business_links values(?,?,'payment')",before.get("source_id"),record);
  audit.log("expensePaymentRecord",record,"paymentRegister",before,payload,null,"approved");return db.queryForMap("select * from app_finance_payments where id=?",payment);
 }
 @Transactional public Map<String,Object> reverse(UUID payment,Map<String,Object> body){access.require("expensePaymentRecord","void");var paymentRows=db.queryForList("select * from app_finance_payments where id=?",payment);if(paymentRows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"付款不存在");var original=paymentRows.get(0);var before=settlement((UUID)original.get("settlement_id"),"void");String reason=Objects.toString(body.get("reason"),"").trim(),reference=Objects.toString(body.get("reference"),"").trim();if(reason.isEmpty()||reference.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"冲销原因与退款流水号必填");var reversed=db.queryForList("select * from app_finance_reversals where payment_id=?",payment);if(!reversed.isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,"付款已经冲销");BigDecimal remaining=((BigDecimal)before.get("paid_amount")).subtract((BigDecimal)original.get("amount"));UUID id=db.queryForObject("insert into app_finance_reversals(payment_id,reference,reason,amount,operator) values(?,?,?,?,?) returning id",UUID.class,payment,reference,reason,original.get("amount"),access.user());db.update("update app_finance_settlements set paid_amount=?,status=? where id=?",remaining,remaining.signum()==0?"pending":"partial",original.get("settlement_id"));var paymentRecords=db.queryForList("select id,status,payload::text as payload from app_records where module_id='expensePaymentRecord' and payload->>'paymentId'=?",payment.toString());db.update("update app_records set status='voided',payload=payload || jsonb_build_object('status','voided','付款状态','已冲销','reversalId',?::text),updated_by=?,updated_at=now() where module_id='expensePaymentRecord' and payload->>'paymentId'=?",id.toString(),access.user(),payment.toString());for(var paymentRecord:paymentRecords)audit.log("expensePaymentRecord",(UUID)paymentRecord.get("id"),"paymentRecordVoided",paymentRecord,Map.of("reversalId",id,"付款状态","已冲销"),paymentRecord.get("status").toString(),"voided");audit.log("expensePaymentRecord",(UUID)before.get("source_id"),"paymentReverse",original,Map.of("id",id,"reason",reason,"reference",reference),null,null);return Map.of("id",id);}
 public List<Map<String,Object>> payments(UUID id){access.require("expensePaymentRecord","view");var source=db.queryForMap("select s.source_id,r.module_id from app_finance_settlements s join app_records r on r.id=s.source_id where s.id=?",id);access.record(source.get("module_id").toString(),(UUID)source.get("source_id"));return db.queryForList("select p.*,r.id as reversal_id,r.reason as reversal_reason from app_finance_payments p left join app_finance_reversals r on r.payment_id=p.id where p.settlement_id=? order by p.created_at",id);}
}
