package com.jada.severe.service;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.LocalDate;
@Service
public class ReportService {
 private final JdbcTemplate db;private final AccessService access;private final AuditService audit;
 public ReportService(JdbcTemplate db,AccessService access,AuditService audit){this.db=db;this.access=access;this.audit=audit;}
 public Map<String,Object> dashboard(){access.require("dashboard","view");var allowed=db.queryForList("select module_id from app_modules where enabled order by sort_order",String.class).stream().filter(m->access.allowed(m,"view")).toList();var args=new ArrayList<Object>(allowed);String in=String.join(",",Collections.nCopies(allowed.size(),"?"));String scope=access.filter(args);var stats=allowed.isEmpty()?List.of():db.queryForList("select module_id,status,count(*) as count from app_records where deleted_at is null and module_id in ("+in+")"+scope+" group by module_id,status order by module_id,status",args.toArray());var result=new LinkedHashMap<String,Object>();result.put("moduleStatusCounts",stats);result.put("myPendingTodos",db.queryForObject("select count(*) from app_todos where assignee=? and status='pending'",Long.class,access.user()));result.put("unreadNotifications",db.queryForObject("select count(*) from app_notifications where user_id=? and read_at is null",Long.class,access.user()));result.put("source","PostgreSQL");return result;}
 public Map<String,Object> daily(LocalDate day){access.require("dailyReport","view");var args=new ArrayList<Object>();args.add(day);args.add(day.plusDays(1));String scope=access.filter(args);var rows=db.queryForList("select module_id,status,payload::text as payload from app_records where deleted_at is null and updated_at>=?::date and updated_at<?::date"+scope,args.toArray());Map<String,Long> counts=new LinkedHashMap<>();java.math.BigDecimal hours=java.math.BigDecimal.ZERO,kilometres=java.math.BigDecimal.ZERO;long maintenance=0;for(var row:rows){String module=row.get("module_id").toString();if(!access.allowed(module,"view"))continue;counts.merge(module,1L,Long::sum);var payload=audit.read(row.get("payload").toString());if(Set.of("machineDispatch","workorder").contains(module)&&Set.of("approved","archived").contains(row.get("status"))){Object h=payload.get("actualHours");if(h!=null)hours=hours.add(new java.math.BigDecimal(h.toString()));}if(module.equals("vehicleDispatch")&&payload.get("actualDistanceKm")!=null&&Set.of("approved","archived").contains(row.get("status")))kilometres=kilometres.add(new java.math.BigDecimal(payload.get("actualDistanceKm").toString()));if(Set.of("maintenance","workorder").contains(module))maintenance++;}var result=new LinkedHashMap<String,Object>();result.put("date",day.toString());result.put("updatedRecordCounts",counts);var usageArgs=new ArrayList<Object>();usageArgs.add(day);usageArgs.add(day.plusDays(1));String usageScope=access.filter(usageArgs);var visibleUsageModules=java.util.stream.Stream.of("vehicleDispatch","machineDispatch").filter(m->access.allowed(m,"view")).toList();usageScope+=" and module_id in ("+(visibleUsageModules.isEmpty()?"NULL":String.join(",",java.util.Collections.nCopies(visibleUsageModules.size(),"?")))+")";usageArgs.addAll(visibleUsageModules);var usage=db.queryForMap("select coalesce(sum(work_hours),0) as hours,coalesce(sum(distance_km),0) as kilometres from app_equipment_usage where completed_at>=?::date and completed_at<?::date and source_id in (select id from app_records where deleted_at is null"+usageScope+")",usageArgs.toArray());result.put("reportedWorkHours",usage.get("hours"));result.put("reportedDistanceKm",usage.get("kilometres"));result.put("maintenanceDocuments",maintenance);result.put("gpsSource","external API; not ingested by this service");audit.log("dailyReport",null,"dailyReport",null,result,null,null);return result;}
 public List<Map<String,Object>> notifications(){access.require("notice","view");return db.queryForList("select * from app_notifications where user_id=? order by created_at desc limit 500",access.user());}
 @Transactional public void readNotification(UUID id){access.require("notice","view");int n=db.update("update app_notifications set read_at=coalesce(read_at,now()) where id=? and user_id=?",id,access.user());if(n==0)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"通知不存在");audit.log("notice",null,"readNotification",null,Map.of("id",id),null,null);}
}
